export const CONSTANTS = {
  LARGE_BET_THRESHOLD: parseFloat(process.env.LARGE_BET_THRESHOLD) || 15000,
  NEW_WALLET_AGE_DAYS: parseInt(process.env.NEW_WALLET_AGE_DAYS) || 7,
  RAPID_ACCUMULATION_THRESHOLD: parseFloat(process.env.RAPID_ACCUMULATION_THRESHOLD) || 50000,
  RAPID_ACCUMULATION_HOURS: parseInt(process.env.RAPID_ACCUMULATION_HOURS) || 24,
  POLL_INTERVAL: 30000,
  CONCENTRATED_BET_THRESHOLD: 0.8,
  COUNTER_CONSENSUS_THRESHOLD: 0.9
};
